title: ー・ー・ー　・ー・ー・　・ー・・　・・・ー

url: https://tuton3kaku.github.io

plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-pagebreak

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ./components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  testimonials:
    output: false
  posts:
    output: true
    permalink: /:year:month:day/

cloudcannon:
  collections:
    pages:
      _icon: 'wysiwyg'
    projects:
      _icon: 'work_outline'
      _subtext_key: subtitle
    testimonials:
      _icon: 'format_quote'
      _subtext_key: position
      _enabled_editors:
        - data

_collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post


# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

twitter:
  username: tuton3kaku

authors:
  shuji:
    name: shuji
    display_name:shuji
    avatar:
  
  shirokuma-89:
    name: shirokuma-89
    display_name: しろくま＠胡瓜
    avatar: 'images/shirokuma-89.jpg'
  poncho:
    name: poncho
    display_name: ぽんちょ
    avatar: 'images/poncho.jpg'
